lib/Capability.js, lib/RestClient.js, lib/utils.js
I ran the library through [CodeClimate](https://codeclimate.com/github/twilio/twilio-node) to see if I could practise some node.js.
I don't know if this is a good idea or the way it might normally be done in node, so I thought I'd put it up for review. Is this a good way to share code between two class constructors?
=> Reduce duplication in Capability and RestClient.

.travis.yml, lib/RestClient.js, package.json, spec/client.live.spec.js
Remove incorrect error data from the data object. Returning an empty body is not an error condition.
=> empty body isn't an error condition :S - fixes #63

lib/index.js
fix 'global leaks detected: MonitorClient, TaskRouterClient, LookupsClient', change semicolons to commas.
=> fix global leaks in index.js

lib/resources/ip_messaging/Services.js
Message - Update and Delete Message
=> Expose update and delete message wrappers

lib/resources/generate.js
After a few days of searching, i found finally the issue of this issue: https://github.com/twilio/twilio-node/issues/117
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/twilio/twilio-node/118)
=> Fixed issue in generate.js when trying to attach undefined object.

lib/Capability.js, lib/TaskRouterCapability.js, package.json, spec/task_router_capability.spec.js, spec/task_router_capability_deprecated.spec.js, spec/task_router_capability_taskqueue.spec.js, spec/task_router_capability_worker.spec.js, spec/task_router_capability_workspace.spec.js
This does the same as #206, but applied to the master branch and the v2 series for this module.
=> Removes jwt-simple from v2.x module

package.json
=> (Next-Gen) Dont include unnecessary files when installing

lib/jwt/AccessToken.js, spec/unit/jwt/accesstoken.spec.js
Migrating TaskRouter to Access Tokens.
=> Adding TaskRouter grant

lib/jwt/AccessToken.js, package.json
as the current version is known to include a vulnerable dependency:
https://snyk.io/test/npm/twilio
=> chore(package): bump jsonwebtoken to ^7.4.1

package.json
=> Updates xmlbuilder, adds  support for unicode characters

lib/base/Page.js
=> Fix paging bug

lib/index.js
=> Brings in the noble FaxResponse.

package-lock.json, package.json
```
> nsp check
(+) 1 vulnerabilities found
┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ sshpk                                                                                         │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS          │ 8 (High)                                                                                      │
├───────────────┼─────────────────────────────────────────────────────── …
```
=> Update request version RE sec. advisory #606

package-lock.json, package.json
- Bump request package for security vulnerabilities.
- Bump locked version of jws from jwonwebtoken module
=> Update request dependency

spec/unit/twiml/MessagingResponse.spec.js
Add a test that verifies that `addChild` and `addText` work correctly when you call them on the same element.
=> Add test for mixed content

index.d.ts
=> Export TwilioClient in typescript definitions

lib/webhooks/webhooks.js, package-lock.json, package.json
=> Updates scmp to version 2.0.0

package-lock.json, package.json
=> Bump packages for security

lib/webhooks/webhooks.d.ts
=> add typedef for validateRequestWithBody

lib/webhooks/webhooks.d.ts, lib/webhooks/webhooks.js
=> refactor to expose utility functions to get expected signature/body hash

package-lock.json
Addresses https://nodesecurity.io/advisories/788
=> Upgrade 'js-yaml' to resolve DOS vulnerability

package-lock.json, package.json
Reverts twilio/twilio-node#406
closes #429
=> Revert "Move @types/express to dev dependencies"

.travis.yml
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
=> Add latest LTS Node.js release to Travis CI config

package-lock.json
Failing build: https://travis-ci.org/twilio/twilio-node/jobs/519477531
Vulnerability: https://www.npmjs.com/advisories/812
jsdoc PR: https://github.com/jsdoc3/jsdoc/pull/1633
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
=> Force 'marked' dependency upgrade to resolve DoS vulnerability

index.d.ts
=> Add missing type for 'validateRequestWithBody'

lib/twiml/TwiML.js, spec/unit/twiml/VoiceResponse.spec.js
=> fix: Stringify TwiML array attributes as space delimited

lib/twiml/TwiML.js, spec/unit/twiml/VoiceResponse.spec.js
=> fix: escape special characters in TwiML attribute values

package-lock.json, package.json
=> chore: upgrade older dependencies

README.md
=> docs: guide for enabling lazy loading

lib/base/RequestClient.js
Fixes #550
Fixes the paramsSerializer passed to axios when making get requests to the twilio REST api.
=> fix: axios expects paramsSerializer not paramSerializer

lib/base/RestException.d.ts, lib/base/RestException.js, spec/unit/base/RestException.spec.js
Add a new property named `details` to `RestException`. `Details` is returned by selective apis to populate extra information about errors. 
The Studio V2 flow api will be returning extra details with flow validation errors. 
=> feat:adds details to rest exception

lib/rest/Twilio.d.ts, lib/rest/Twilio.js
A quick refactor based on [this comment](https://github.com/twilio/twilio-node/pull/563/files/4d52072aee89d85275d53ea4aa0a451a988ec0b0#r413872428).
=> chore: logic refactor

lib/rest/autopilot/v1/assistant.d.ts, lib/rest/autopilot/v1/assistant.js, lib/rest/autopilot/v1/assistant/query.d.ts, lib/rest/autopilot/v1/assistant/query.js, lib/rest/autopilot/v1/assistant/task/field.d.ts, lib/rest/autopilot/v1/assistant/task/field.js, lib/rest/conversations/v1/conversation/message/deliveryReceipt.js, lib/rest/video/v1/composition.d.ts, lib/rest/video/v1/composition.js, lib/rest/video/v1/recording.d.ts, lib/rest/video/v1/recording.js, lib/rest/voice/v1/ipRecord.d.ts, lib/rest/voice/v1/ipRecord.js
=> docs: convert markdown links to jsdoc formatted links

package.json
- critical vulnerability in 0.19.2
- https://github.com/axios/axios/pull/341
- fixes #631
=> fix: axios update to v0.21.1

lib/rest/Studio.d.ts, lib/rest/Studio.js
https://issues.corp.twilio.com/browse/DI-702
=> fix: shortcut syntax for new non-GA versions

lib/webhooks/webhooks.js
=> fix: validation failing due to params

package.json
Fixes #660
A short description of what this PR does.
=> chore: upgrade url-parse

package.json
=> chore: bump lodash and eslint per npm audit

package.json
Upgrading `url-parse` dependency to handle security issue: https://github.com/advisories/GHSA-hh27-ffr2-f2jc
=> chore: Updated url-parse dependency to address security issue

.github/workflows/deploy.yml
Tested [here](https://github.com/shwetha-manvinkurke/twilio-node/runs/4098165390?check_suite_focus=true)
=> fix: node setup wf step

package.json
=> chore: bump axios to latest

package.json
=> chore: update url-parse dependency

.gitignore, package.json, sonar-project.properties
=> test: drop nyc

README.md
Fixes #762 
Closes #762 
A full stop is added in a sentence in README.md file
=> docs: a full stop is added in README.md file

spec/unit/rest/Twilio.spec.js
Internal Jira link: [DI-2164](https://issues.corp.twilio.com/browse/DI-2164)
=> fix: useragent regrex unit test for RC branch

lib/base/RequestClient.js, spec/integration/holodeck.js
Replaces q promises with native promises in hand-crafted code.
=> chore: replace q with native promises

lib/base/utility.ts, spec/unit/base/utility.spec.ts
Usage will be added with later change.
=> feat: add path param validator

.github/workflows/test-and-deploy.yml
=> chore: add rc branch to test&deploy workflow

lib/rest/Twilio.ts
Related PR: https://code.hq.twilio.com/twilio/librarian/pull/457
JIRA- [DI-2350](https://issues.corp.twilio.com/browse/DI-2350)
=> feat: Changes to twilio.ts file for TSDoc

src/jwt/AccessToken.ts
Reverts export strategy to same as v3.
Fixes https://github.com/twilio/twilio-node/issues/919
=> fix: revert the structural changes to the AccessToken class/namespace

src/base/Version.ts
Fix the issue of unhandledRejection
[github issue](https://github.com/twilio/twilio-node/issues/949).
=> fix: fix unhandledRejection

.github/ISSUE_TEMPLATE/feature-request.yml
Added feature request issue template
=> chore: added feature request issue template

package.json
Upgraded dependencies for semver which was vulnerable to Regular Expression Denial of Service
https://github.com/twilio/twilio-node/issues/959
After upgrading semver versions:
├─┬ @babel/preset-env@7.23.2
│ ├─┬ @babel/core@7.21.4
│ │ └── **semver@6.3.1** deduped
│ ├─┬ @babel/helper-compilation-targets@7.22.15
│ │ └── **semver@6.3.1** deduped
│ ├─┬ @babel/plugin-syntax-unicode-sets-regex@7.18.6
│ │ └─┬ @babel/helper-create-regexp-features-plugin@7.22.15
│ │   └── **semver@6.3.1** deduped
│ ├─┬ @babel/plugin-transform-class-properties@7.22.5
│ │ └─┬ @babel/helper-create-class-features-plugin@7.22.15
│ │   └── **semver@6.3.1** deduped
│ ├─┬ babel-plugin-polyfill-corejs2@0.4.6
│ │ └── **semver@6.3.1** deduped
│ └── **semver@6.3.1**
├─┬ jest@29.7.0
│ └─┬ @jest/core@29.7.0
│   ├─┬ …
=> chore: upgraded semver versions

.github/workflows/test-and-deploy.yml, package.json
Adds the Node LTS version in workflow
Earlier it was removed under this [PR](https://github.com/twilio/twilio-node/pull/978) but this issue is now resolved 
=> chore: add lts version

.github/workflows/test-and-deploy.yml
A short description of what this PR does.
=> chore: disable-cluster-test

CHANGES.md, UPGRADE.md
=> feat!: MVR preparation

package.json
jsonwebtoken fixed the semver vulnerability in [v9.0.2](https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md#902---2023-08-30). Upgrading the version of jsonwebtoken here to avoid downstream vulnerability.
=> chore: upgrading jsonwebtoken to fix vulnerability

src/base/BaseTwilio.ts
ContentType is required in POST and PUT methods. Adding the support for PUT.
=> chore: adding contentType in post and put

.github/workflows/test-and-deploy.yml
=> chore: add v22 support

package.json
Update Axios version
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6671926
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6671926
=> chore: update axios version

UPGRADE.md
=> feat!: MVR release preparations

spec/unit/credential_provider/ClientCredentialProvider.spec.ts, spec/unit/credential_provider/NoAuthCredentialProvider.spec.ts, spec/unit/credential_provider/OrgsCredentialProvider.spec.ts
Correcting the message to be displayed on unit tests
=> chore: fix message on unit tests

src/http/bearer_token/ApiTokenManager.ts, src/http/bearer_token/OrgsTokenManager.ts
Update IAM token endpoint from Preview to IAM
=> chore: Update IAM token endpoint from Preview to IAM

spec/cluster/orgs_api.spec.ts
Cluster test moved from preview iam to iam for token generation
=> chore: fix cluster test

package.json
Axios version less than 1.11.0 introdcues transitive [vulnerability](https://github.com/twilio/twilio-cli/security/dependabot/94) in twilio-cli. 1.11.0 fixes it.
=> chore: upgrade axios version

src/twiml/TwiML.ts
Converting from any to string type for better type handling
=> fix: converting from any to string type

.github/workflows/close-stale-issues.yml
Adding workflow to close stale issues similar to twilio-cli. See [here](https://github.com/twilio/twilio-cli/pull/477)
1. It keeps issues with tag "type: community enhancement" and "type: twilio enhancement" as open since they are feature requests.
2. Sample [issue](https://github.com/twilio/twilio-node/issues/1113) marked as stale and closed.
3. Sample workflow [run](https://github.com/twilio/twilio-node/actions/runs/16824666278).
=> chore: add close-stale-issues workflow

package.json, tsconfig.json
The @types/node package is using newer TypeScript features (disposable resources with Symbol.dispose, Symbol.asyncDispose, and Disposable interface) that aren't supported by the current TypeScript version. Due to this, the tests were failing, see [here](https://github.com/twilio/twilio-node/actions/runs/17036303368/job/48289796016).
To fix this, we have upgraded to use the latest typescript version 5.9.2. The previous typedoc version also supported only till 5.0.x, so updated it to the latest version as well.
Tested by making api calls, works fine.
The failing test is due to a 4xx error coming from Orgs API fetch account endpoint.
=> chore: upgrade typescript and typedoc version

src/http/bearer_token/ApiTokenManager.ts, src/http/bearer_token/OrgsTokenManager.ts
Changing token endpoint to oauth.twilio.com and using endpoint v2/token.
Similar to #1089 
=> chore: change oauth token endpoint
