- .gitignore
- .npmignore
This commit improves the `.gitignore` and `.npmignore` files.
Here are the two main changes:
1. dot files are now in a white-list rather than a black-list
2. log files are by default ignored (like the `npm-debug.log` file)
This shouldn't add any breaking changes but could cause a conflict with one of my earlier pull-requests (#60) where I also modified the `.gitignore` file so as to not commit test coverage files (the whole `spec/coverage` folder).
If this is the case, the `.gitignore` file this commit is newer and should prevail.
> Improved .gitignore and .npmignore

- lib/webhooks.js
It replaces the manual url creation by `string concatenation` with the safer, native, `url.format()` method.
This is not a bug fix, just a slight improvement that delegates url handling to Node.js's core `url` module.
> Replaces manual url creation by native url formating method

- lib/RestClient.js
Right now the 'dateSent' property isn't getting automatically formatted as a date. This field is returned in the `getSms` response callback.
I'd like to add that this method of converting dates should be reconsidered for something more flexible. I'd propose searching *all* fields for things that look datey, or convert to a valid date when they're `Date.parse()`'d. This would add a little processing overhead, though.
PS: I fudged up this pull request by creating another pull request on my own branch, but am unsure how to undo what I did D:
> add dateSent to list of date converted strings

- lib/Capability.js
- spec/capability.spec.js
The changes in this pull request would enable the following ease-of-use functionality:
```
var capToken = twilio.Capability(accountSid, authToken)
.allowClientIncoming('alice')
.allowClientOutgoing('app123')
.generate();
```
This change is non-breaking.
> Added chainability to Capability methods for ease-of-use.

- package.json
The dependency module request v2.27.x relies on tunnel-agent which does not fully support node 0.12.x.
Testing it with request v2.55.x, everything seems to work fine.
> updated dependencies - request 2.27.x -> 2.55.x

- package.json
- spec/client.core.spec.js
1. Use local http server to verify client timeout.
2. Bump jasmine-node to version 2.0.x.
> Fix flaky client tests

- index.html
Adds a couple of other things too:
* 403 response when failing to validate the request
* splits up the two examples of `validateExpressRequest` so they are more obvious
* adds `app.listen` line to start server
* adds spaces between `//` and comments
> Updates docs to use bodyParser instead of express.urlencoded

- lib/TaskRouterCapability.js
- lib/TaskRouterWorkerCapability.js
- spec/task_router_capability.spec.js
- spec/task_router_capability_deprecated.spec.js
- spec/task_router_capability_worker.spec.js
- Allow fetching Reservations under a Worker by default
- Allow updating Reservations under a Worker
> Loading Reservations under a Worker by default in TaskRouter JS SDK

- lib/AccessToken.js
The package.json for `twilio-node` specifies an `underscore` version of `1.x`. However, the `_.includes` function alias only appeared in `underscore@1.8.x`, so the library is broken for older underscore versions, even those these should be valid according to the package.json.
`_.contains` is a valid alias in all `1.x` versions and so is a better choice to offer the widest compatibility - this is important because underscore may often be included as a peer dependency.
> Use _.contains instead of _.includes

- lib/jwt/Capability.js
- lib/jwt/TaskRouterCapability.js
- package.json
- spec/unit/jwt/task_router_capability.spec.js
- spec/unit/jwt/task_router_capability_taskqueue.spec.js
- spec/unit/jwt/task_router_capability_worker.spec.js
- spec/unit/jwt/task_router_capability_workspace.spec.js
We were using two JWT dependencies, jwt-simple and jsonwebtoken. Issue #205 points out a vulnerability in jwt-simple 0.1.0 which lay within the dependencies. Removing it completely in favour of jsonwebtoken was the easiest course of action.
We could probably do this for master and the current version of twilio-node too. Less dependencies and less vulnerabilities would be awesome.
> Remove the jwt-simple dependency.

- package.json
Replaces dependency on deprecated node-uuid with uuid.
Fixes #209
> (NextGen) Updates request to 2.79.x.

- package.json
Currently, tools like Snyk report `twilio` as vulnerable via its `moment` dependency (https://snyk.io/test/npm/moment/2.14.1).
> chore(package): bump moment to 2.18.1

- lib/jwt/AccessToken.js
- spec/unit/jwt/AccessToken.spec.js
As the name IpMessaging has been deprecated, this changes the grant to the name `ChatGrant`. It is the same as the existing `IpMessagingGrant` so is just a straight name swap for developers.
`IpMessagingGrant` will continue to work and now inherits from `ChatGrant`. It will spit out a deprecation notice though.
I also silenced deprecations in test output as part of this.
> Adds ChatGrant to jwt. Deprecates IpMessagingGrant.

- lib/webhooks/webhooks.js
The option for the webhook URL is actually called `url` not `webhookUrl`, as seen here:
```
if (options.url) {
// Let the user specify the full URL
webhookUrl = options.url;
}
```
> Correcting the hint for webhook URL option

- .travis.yml
- package.json
Why?
To verify that there are not known security vulnerabilities in our dependencies so we can actively address them when found.
Changes:
- add nsp as dev dependency (jshint was moved to be alphabetical by npm
cli)
- add nsp script to package.json
- add nsp to the make test command
> Node Security Project - Add nsp check script to warn for dependency vulnerabilities

- package.json
Updates the request version to 2.83.x to get rid of the uuid deprecation
warning on install.  Request was updated almost a year ago to use a new
uuid module.  Since twilio depends on an older version of request, the
installation continues to emit a deprecation warning.  This commit fixes
the deprecation warning on install.
[It looks like there were no breaking changes](https://github.com/request/request/compare/v2.81.1...master) to request in this upgrade.
> deps: bump request version to 2.83.x

- package-lock.json
- package.json
Addresses recent NSP advisory regarding ReDoS vulnerability.
https://github.com/moment/moment/commit/69ed9d44957fa6ab12b73d2ae29d286a857b80eb
> Update momentjs to address NSP 532 ReDoS advisory.

- lib/webhooks/webhooks.js
`url.format` (https://nodejs.org/api/url.html#url_url_format_urlobject) treats the `pathname` option as the path _excluding_ query string, so any `?` get encoded as `%3F'.
Since (express) `request.originalUrl` may contain the query string, it is incorrect to pass it to `url.format` as a `pathname`.
This PR may not be the best solution, but is submitted to illustrate what the issue is.
When the `request.originalUrl` contains a `?` it should _not_ be URL-encoded as `%3F`.
https://github.com/twilio/twilio-node/issues/306
> Fix X-Twilio-Signature validation when URL has ?

- lib/base/RequestClient.js
Hey guys.
Is it possible to add this flag 'forever' as an option in your RequestClient class request method? In that case it will be possible to inherit your class and override this option.
Reason: forever: true doesn't work correctly with AWS lambda functions and we need a way how to override this option without rewriting HttpClient from scratch. Execution of your library methods will return a socket hang up exception from time to time in AWS lambdas, because of the lambdas life cycle.
> Add 'forever' as an option to RequestClient request method.

- lib/base/serialize.js
When running the snippet below, in some node versions the code fails because twilio-node is unable to format the given `startDate` and `endDate` parameters.
```javascript
// Download the helper library from https://www.twilio.com/docs/node/install
// Your Account Sid and Auth Token from twilio.com/console
const accountSid = 'ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);
client.calls.feedbackSummaries
.create({
startDate: new Date(Date.UTC(2008, 0, 2)),
endDate: new Date(Date.UTC(2008, 0, 2))
})
.then(feedback_summary => console.log(feedback_summary.sid))
.done();
```
I've narrowed down the issue to the following line:
https://github.com/twilio/twilio-node/blob/master/lib/base/serialize.js#L22
This PR …
> use _.isDate to check if object is a Date object

- lib/jwt/AccessToken.js
- package-lock.json
- spec/unit/jwt/AccessToken.spec.js
https://issues.corp.twilio.com/browse/CLIENT-4492
To support JS Clients per this spec:
https://paper.dropbox.com/doc/Proposal-FPA-Token-Format-for-Programmable-Voice-SDKs-xhdFHD6N3aPW9GRp4dXNX
> Add incoming.allow to AccessToken VoiceGrant

- package-lock.json
- package.json
Upgrading lodash to resolve https://snyk.io/vuln/npm:lodash:20180130
CVE-2018-3721 
Disclosed: 30 Jan, 2018
Published: 14 Feb, 2018
(The twilio version in package-lock was out of date and `npm install` auto updated it to the current twilio-node version in package.json: 3.15.1)
> Upgrade lodash

- lib/twiml/FaxResponse.js
- lib/twiml/MessagingResponse.js
- lib/twiml/VoiceResponse.js
- package-lock.json
- spec/unit/twiml/VoiceResponse.spec.js
Allow adding arbitrary text under TwiML nodes via the new method `addText`
> Add addText method to TwiML classes

- lib/rest/Twilio.js
- spec/integration/rest/Twilio.spec.js
Add validateSslCertificate to check whether we can successfully make requests to the endpoint that uses the new SSL certificate.
> Add validateSslCertificate to node client

- lib/twiml/FaxResponse.js
- lib/twiml/MessagingResponse.js
- lib/twiml/TwiML.js
- lib/twiml/VoiceResponse.js
- spec/unit/twiml/MessagingResponse.spec.js
- spec/unit/twiml/VoiceResponse.spec.js
- Creates a basic class inheritance between `Response`s and `TwiML` (added)
- Moves `addText()` method to parent `TwiML` class
- Adds a `addChild()` method to anything that inherits `TwiML`
> Allow creating generic twiml nodes

- lib/index.js
- lib/webhooks/webhooks.js
- package-lock.json
- package.json
- spec/validation.spec.js
This PR:
- Adds a request body validator that accepts a string, for validating POST body that's not form data
- Gracefully (backwards-compatibly) removes unsupported, useless code from the Express Middleware
- Refactors tests to not stand up an express server, mocking requests instead
> Add a request body validator

- index.d.ts
- lib/jwt/AccessToken.d.ts
- lib/webhooks/webhooks.d.ts
This PR fixes different TypeScript related binding issues found in #374, #376 and by @nash-md. Specifically this fixes:
- Exporting TwiML constructors correctly as `twilio.twiml.VoiceResponse` etc.
- Making all options in `AccessTokenOptions` optional to not force the user to provide all if one is present
- Setting the algorithm argument in `toJwt` for AccessTokens to optional since a default value is present
- Add `allowIncoming` as new option for `VoiceGrantOptions`
- Marking the `RequestValidatorOptions` values as optional
<details>
<summary>Script used to verify changes</summary>
```ts
import twilio = require('twilio');
// creating a client
const client = twilio(
process.env.TWILIO_ACCOUNT_SID,
process.env.TWILIO_AUTH_TOKEN
);
// create TwiML
const myTwiml = new …
```
> Fix TypeScript related issues

- lib/jwt/ClientCapability.d.ts
- spec/unit/jwt/ClientCapability.spec.js
Included TTL option in `ClientCapability` and test code to cover this.
I was not sure about write another condition in unit test where a token is generated so I wrote a new unit test to cover TTL option. Let me know If I should change it and move the condition to another test.
> Include TTL option in ClientCapability

- lib/webhooks/webhooks.js
- spec/validation.spec.js
Our internal system sends the bodySHA256 parameter as hex, not base64, so this PR fixes that.
> Switch body validator to use hex instead of base64

- lib/base/RequestClient.js
After running `npm test` the log mentions a deprecation warning:
(node:12636) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsause the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
This fix should be in line with supporting Node 6/8 and other areas of the code are already using Buffer.from(...).
> DeprecationWarning: Buffer()

- lib/rest/Twilio.js
This error message is a little less confusing when a user is passing an accountSid but it doesn't start with AC.
> Better error message when username doesn't start with AC

- package-lock.json
- package.json
I am pretty sure that all `@types/*` dependencies are dev-only.
> Move @types/express to dev dependencies

- package.json
Pinning down moment to an exact version can lead to unsolvable requirements in bigger projects. Never but compatible versions of moments should be allowed.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
> Allow using newer moment versions

- lib/webhooks/webhooks.js
- package-lock.json
- spec/validation.spec.js
Implemented a check in lib/webhooks/webhooks.js's webhook() middleware to check if the X-Twilio-Signature header exists or not.
If the request is not made from Twilio servers then we won't have *X-Twilio-Signature* header in the request and the middleware will throw cryptic error from *validateRequest()* function.
> Check X-Twilio-Signature in webhook middleware

- lib/webhooks/webhooks.d.ts
Hello,
In the [docs,](https://www.twilio.com/docs/usage/tutorials/how-to-secure-your-express-app-by-validating-incoming-twilio-requests#disable-request-validation-during-testing) it says to secure Express app by validating incoming Twilio requests with validate property and has used validate property only. The [twilio.Webhook()](https://github.com/twilio/twilio-node/blob/81329c7cf756c805dc843903ba4911891b484d60/lib/webhooks/webhooks.d.ts#L24) method does not accept validate property alone and gives an error. While if you check it's Javascript [code](https://github.com/twilio/twilio-node/blob/81329c7cf756c805dc843903ba4911891b484d60/lib/webhooks/webhooks.js#L154), you can clearly know that all properties are optional and validate is by default true. 
Code: 
```
const shouldValidate = …
```
> WebhookOptions interface's properties made optional

- README.md
Hello! 
First off, thanks for maintaining such a useful library. :heart: I truly appreciate it.
There is a bunch of really helpful code in the examples folder, that I didn't discover until late in the game. Linking to the examples in the README seems like an easy fix to help other people avoid my mistake.  Thanks and have a great day.
> Add link to code examples in README

- lib/webhooks/webhooks.js
- spec/validation.spec.js
[X-Twilio-Signature check](https://github.com/twilio/twilio-node/blob/6585f327e4f681971dc3eddf40ca5840adf685dc/lib/webhooks/webhooks.js#L176) is added before [checking](https://github.com/twilio/twilio-node/blob/6585f327e4f681971dc3eddf40ca5840adf685dc/lib/webhooks/webhooks.js#L182) the validate option. The request will fail even if [validate option](https://github.com/twilio/twilio-node/blob/6585f327e4f681971dc3eddf40ca5840adf685dc/lib/webhooks/webhooks.d.ts#L32) is set to false. If a request is sent from POSTMAN on dev/test environment, which means the validate option is false, so there is no need to check if the header is present or not. Similarly, if a test is written for Express route in my code, the middleware will fail despite the fact that validate option is false.
It also checks …
> Request middleware fails on validate set to false

- lib/jwt/taskrouter/TaskRouterCapability.d.ts
As per this:
https://github.com/twilio/twilio-node/blob/master/lib/jwt/taskrouter/TaskRouterCapability.js#L23
PolicyOption has a property `allow`
In types file here:
https://github.com/twilio/twilio-node/blob/master/lib/jwt/taskrouter/TaskRouterCapability.d.ts#L42
it is `allowed`
> Typing fix for PolicyOptions

- README.md
- examples/example.js
- lib/base/RequestClient.js
- lib/http/request.js
- package-lock.json
- package.json
- spec/unit/base/RequestClient.spec.js
Proposal to Issue #481
Right now there is no way for a user to specify a CA bundle to replace the default one that `request` ships with.
According to [the request docs](https://github.com/request/request#tlsssl-protocol) you can specify it in the `options` object passed to `request`.
This change offers a simple solution by setting a path to your CA bundle as an environment variable: 
`TWILIO_CA_BUNDLE=/path/to/cert.pem`
Test cases have been included to ensure that the specified CA bundle is used, and that the original behavior of not including it in `options` remains unchanged if it is not specified.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is …
> Added the ability for users to specify a CA bundle for HTTPS requests

- lib/http/request.d.ts
Adding optional ca to the request options interface for specifying a CA bundle.
> Adding optional ca for specifying CA bundle.

- .travis.yml
> Allow for auto-deploy on tagged releases

- .gitignore
- lib/jwt/AccessToken.js
- spec/unit/jwt/AccessToken.spec.js
Fixes #438
Resolves missing identity value in token when it's not a string begin passed in the `AccessToken` constructor.
The specs of the issue ticket suggest throwing an error when identity is passed as an integer. Originally, I took this approach but I quickly realized this would cause breaking changes for anyone passing numeric values in identity option. I do not believe this is error worthy because simple converting the value to a string solves the down stream implication in the jwt.
```javascript
if (_.isInteger(options.identity)) { options.identity = new String(options.identity); };
```
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided …
> Fixes missing identity value in token when it's not a string

- lib/webhooks/webhooks.js
replace all matches of `%3F` for `?`
> Fix escape url

- lib/webhooks/webhooks.js
- spec/validation.spec.js
> added request validation for urls with and without ports

- lib/webhooks/webhooks.d.ts
This update the type definition according to `webhooks.js`. Add `url` to type definition of `WebhookOptions` so that it proper extends `RequestValidatorOptions`. This let typescript users to pass `url` with the `webhook` express middleware.
> fix: Add optional 'url' property to the webhook request validator type definition

- lib/base/deserialize.js
- lib/base/serialize.js
- package-lock.json
- package.json
- spec/unit/base/deserialize.spec.js
- spec/unit/base/serialize.spec.js
> fix: replace moment with dayjs

- lib/index.js
- lib/rest/Twilio.d.ts
- lib/rest/Twilio.js
I have done some tweaking and added a proof of concept lazy loading to the Twilio module to see if it improves the loading time, see the [compare](https://github.com/twilio/twilio-node/compare/3d0e4a1de19476337f2ac4413b6c612c58b3c721...Mediapioniers:faster-requires) for reference.
When lazy loading is disabled(default), test returns a 600ms timeframe:
```node
console.time('Twilio');
const Twilio = require('./index');
const client = new Twilio('AAAAAAAAAAAAAAAAAAAAAAAA', 'AUTHTOKEN');
console.timeEnd('Twilio');
```
When lazy loading is enabled, test returns a 16ms timeframe:
```node
console.time('Twilio');
const Twilio = require('./index');
const client = new Twilio('AAAAAAAAAAAAAAAAAAAAAAAA', 'AUTHTOKEN', { lazyLoading: true });
console.timeEnd('Twilio');
```
The require of Twilio has …
> feat: Faster requiring using optional lazy loading

- lib/webhooks/webhooks.js
The url parameter is documented in `validateExpressRequest` but not in `twilio.webhook` which uses the same optional parameter.
> docs: add url parameter documentation in twilio.webhook()

- examples/typescript/example.ts
- lib/twiml/VoiceResponse.d.ts
This allows users to use a string as the first argument with TypeScript enabled.
> fix: Add method overload to VoiceResponse.prototype.play

- lib/base/RestException.js
Enables stack traces (.stack) that come with 'Error'.
Fixes #548
> fix: refactor 'RestException' to properly extend 'Error'

- README.md
- lib/rest/Twilio.d.ts
- lib/rest/Twilio.js
- package.json
- spec/unit/rest/Twilio.spec.js
> feat: add regional support

- lib/rest/monitor/v1/alert.js
Fixes #585
This fixes the issue with the alert endpoint not using the time when specifying the date/time to limit the results. 
> fix: use datetime instead of date for alert start/end date params

- lib/base/RequestClient.js
- lib/http/response.d.ts
- lib/http/response.js
The default HTTP client stores 'Last Request' and 'Last Response' information for access to more data about the raw API request/response. The response object did not contain the headers until now.
> feat: include API response headers in 'Last Response'

- package.json
Ignoring low severity vulnerabilities until lodash issue is resolved: https://www.npmjs.com/advisories/1523
> fix: upgrade dependencies and ignore low severity vulnerabilities

- package.json
> fix: allow lower versions of typescript (2.5)

- lib/base/Version.d.ts
- lib/base/Version.js
- spec/unit/base/Version.spec.js
Prevent throwing a `RestExpection` on `3XX` response status code. https://github.com/twilio/twilio-node/issues/613
Questions/Notes:
- There is similar logic in other http request wrappers (`update`, `remove`, `create`). Do I need to change it as well?
- I'll add tests if/when the general approach is approved
> fix: Prevent throwing an exception on 3xx response status code

- README.md
- lib/base/RequestClient.js
- lib/rest/Twilio.d.ts
- lib/rest/Twilio.js
https://issues.corp.twilio.com/browse/DI-947
> feat: add http logging for Node JS

- package.json
> chore: Move @types dependencies to peerDependencies

- lib/webhooks/webhooks.js
Reverts https://github.com/twilio/twilio-node/pull/621
621 breaks `validateExpressRequest`.
Replacing of these URL-encoded characters is not correct since ":", and "@" are reserved characters that should be URL-encoded and are probably being URL-encoded by most customers (correctly using encodeURIComponent instead of something incorrect like encodeURI)
https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options
> fix: url encoding for validateExpressRequest

- lib/jwt/AccessToken.d.ts
The docs show things like adding an identity to an access token like this:
```js
const accessToken = new AccessToken(
ACCOUNT_SID,
API_KEY_SID,
API_KEY_SECRET,
);
accessToken.identity = 'example';
```
And similar for options in grants. But the types don't support this and enforce TS users to set them in the options passed to the constructor.
This adds sthe types for the properties for AccessTokens and each *Grant.
> fix: adds property types for AccessToken and Grants

- README.md
- examples/express.js
- lib/webhooks/webhooks.js
- package.json
- spec/validation.spec.js
This PR fixes issue when the `validateExpressRequest` is used for webhook validation when the content-type is application/json. 
Note: We expect the `request.rawBody` populated for the validation in this case. 
Fixes #657
> fix: fix validateExpressRequest issue

- index.d.ts
- lib/index.js
Exposes the internal `RequestClient` so users don't need to import relying on `twilio-node's` file structure, ex: `const RequestClient = require('twilio/lib/base/RequestClient');` and can instead import via:
```js
const twilio = require('twilio');
const { RequestClient } = twilio;
```
The use case is when users are writing some type of custom client but they don't want to directly access `axios`, etc and instead want to lean on Twilio's existing client, for example:
```js
const twilioClient = twilio(accountSid, authToken, {
httpClient: new CustomRedirectClient('http://localhost:8080/mock-server', new RequestClient()),
});
```
Adds `RequestClient` to typedefs.
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added the necessary documentation …
> chore: expose internal RequestClient to users at top level

- .nycrc.json
- .travis.yml
- package.json
- sonar-project.properties
Adds SonarCloud and TravisCI integration
A short description of what this PR does.
> chore: integrate with SonarCloud

- examples/typescript/example.ts
- lib/webhooks/webhooks.d.ts
- package.json
@types/express only supports TypeScript 3.5+ versions while we support TypeScript 2.9+. This PR removes all of the @types dependencies as dev dependencies except for @types/node for environment variables.
> fix: remove @type/express 

- lib/webhooks/webhooks.js
- spec/validation.spec.js
[Conversations API `onConversationAdd` webhook](https://www.twilio.com/docs/conversations/conversations-webhooks#onconversationadd) `MessagingBinding.Address` parameter can be either `string` or `array<string>` (you can see it underneath the parameters table in the **Note** section). twilio-node library will always fail to validate such webhooks because array parameters are not supported. In this pull-request I added a support for such parameters, but nothing more than that — deeply nested arrays, or object parameters are still not supported and I am not sure If they should be.
> fix: webhook validation with an array parameter

- lib/base/RequestClient.js
- spec/unit/base/RequestClient.spec.js
This makes it easier to wrap the client and get access to the response headers.
> feat: add API response headers to the returned response

- lib/jwt/ClientCapability.d.ts
Resolves #699
Makes ttl optional in ClientCapabilityOptions since the constructor doesn't require a value and provides a default.
> fix: make ttl optional in ClientCapabilityOptions

- README.md
- lib/rest/Twilio.d.ts
- lib/rest/Twilio.js
Internal JIRA ticket: [DI-2059
](https://issues.corp.twilio.com/browse/DI-2059)
> chore: Defaults lazyloading to true

- lib/jwt/AccessToken.d.ts
- lib/jwt/AccessToken.js
- spec/unit/jwt/AccessToken.spec.js
Internal JIRA link: [DI-1116](https://issues.corp.twilio.com/browse/DI-1116)
- Changes to be included in upgrade guide
> chore!: Remove deprecated ConversationsGrant 

- lib/jwt/AccessToken.d.ts
- lib/jwt/AccessToken.js
- spec/unit/jwt/AccessToken.spec.js
Internal Jira Link: [DI-1115](https://issues.corp.twilio.com/browse/DI-1115)
- Changes to be included in upgrade guide
> chore!: Remove deprecated IpMessagingGrant

- lib/rest/api/v2010/account/incomingPhoneNumber.ts
- lib/rest/events/v1/subscription.ts
- lib/rest/lookups/v1/phoneNumber.ts
- lib/rest/proxy/v1/service/session.ts
- lib/rest/verify/v2/service/entity/challenge.ts
Also fix double accountSid name.
> fix: properly serialize various parameters

- package.json
Removes `q` as a saved dependency as all handcrafted and auto-generated code now no longer uses it in-favor of native promises. Removes unused `rootpath` dependency.
> misc: remove unused dependencies

- .eslintrc.json
- .jshintrc
- lib/base/BaseTwilio.ts
- spec/unit/rest/Twilio.spec.js
To better illustrate that an Account SID is required when using an API key to init the client.
Fixes #600
> fix: give more descriptive error for accountSid init issues

- package.json
Relates to https://github.com/twilio/twilio-node/issues/846 and https://github.com/twilio/twilio-node/pull/847
twilio-node v3 supports Node v6/8/10 which are not supported by jsonwebtoken v9. But, after reviewing the vulnerabilities in jsonwebtoken v8, our helper lib is not affected (we don’t verify signatures, only do the signing, and we use default algorithms). This change is to bypass audit failures for v3. Note that v4 does not bypass the audit and uses jsonwebtoken v9.
> test: bypass audit failures until v4 release

- .github/workflows/pr-lint.yml
- .github/workflows/test-and-deploy.yml
- Dockerfile
Fixes warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> chore: upgrade GitHub Actions dependencies

- lib/rest/studio/v2/flow/flowRevision.ts
- package.json
This removes TypeScript errors for non-matching types.
> fix: stringify non-string path param response properties

- lib/base/RestException.ts
- spec/unit/base/RestException.spec.ts
Fixes https://github.com/twilio/twilio-node/issues/715
if the messageBody is malformed then there will be a json parse error since the only check to allow parse is whether the body be a string or not. If we wrap the parse in a try catch, we can code a gentler response.
- Assumptions
- ~~**1: Assuming that details is where the error details are located**~~
- ~~I have populated the details property inside the exception object with the parse error `{error: bodyParseError}`. For more information, peruse the new unit test described with "should test serialize from improper json string".~~ 
- on malformed json response_body, the exception should contain undefined properties except for message which is overwritten by the call to super.
- **2: Assuming that the logger is catching the …
> fix: update SMS messaging parse error

- lib/base/Version.ts
- spec/unit/base/Version.spec.js
[Internal Jira Link
](https://issues.corp.twilio.com/browse/DI-2414)
Done now only gets called once.
> fix: done only gets called one in each

- lib/jwt/AccessToken.ts
- spec/unit/jwt/AccessToken.spec.js
JIRA: [DI-2445](https://issues.corp.twilio.com/browse/DI-2445)
Making Identity required in the AccessToken constructor.
> feat!: Making AccessToken Identity required

- lib/base/RequestClient.ts
- lib/http/request.ts
- spec/unit/base/RequestClient.spec.js
No longer store the CA bundle in the `LastRequestOptions` as it doesn't change from request to request. Also update tests.
> chore: cleanup CA bundle setting of request client

- README.md
- lib/base/BaseTwilio.ts
- lib/base/RequestClient.ts
- spec/integration.spec.js
- spec/unit/base/RequestClient.spec.js
Adds auto-retry with exponential backoff feature to auto-retry requests to the API when the API returns a 429 Too Many Requests error response. This feature is disabled by default.
Adds how-to docs for this feature to the README.
This PR is based on changes made in #741 (Thanks, @bobtfish!)
> feat: Add auto-retry with exponential backoff

- lib/twiml/TwiML.ts
- package.json
Readds test:typescript to test rule, also makes a small Twiml fix
> chore: re-add test:typescript to test rule

- lib/twiml/VoiceResponse.ts
`break` is a keyword in JS, but it is allowed for method names. Therefore we want to rename `break_()` methods to `break()`
> fix: use break() for method names rather than break_()

- Dockerfile
- Makefile
The `test-docker` make rule got lost when we merged in the RC branch, restoring it here
> fix: restore test-docker rule

- src/index.ts
For CommonJS exports, namespaces and functions can be merged. This allows the compiler to merge the function with value properties instead of manually assigning each one, while also exposing types at the top level of the module export.
Fixes #913
> fix: Export values and all type information

- .github/workflows/test-and-deploy.yml
- package.json
- spec/cluster/package.json
- spec/cluster/test.spec.ts
- spec/cluster/tsconfig.json
- spec/cluster/webhook.spec.ts
[DI-2566](https://issues.corp.twilio.com/browse/DI-2566)
> test: refactor cluster tests for pack output

- src/base/BaseTwilio.ts
- tsconfig.json
The `RequestOpts` interface was incorrectly using the `Headers` type from the DOM lib. This produces an error for TypeScript users if they have `skipLibCheck` set to `false` and are not including the DOM TypeScript lib:
```
node_modules/twilio/lib/base/BaseTwilio.d.ts:22:19 - error TS2304: Cannot find name 'Headers'.
22         headers?: Headers;
~~~~~~~
Found 1 error in node_modules/twilio/lib/base/BaseTwilio.d.ts:22
```
This PR also updates the `lib` in `tsconfig.json` to match the target. This makes it so that the DOM TypeScript lib is not included, since by default the DOM lib is included unless specified otherwise. I verified that this change would have caught this issue.
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue …
> fix: use correct Headers type

- package.json
Per https://github.com/twilio/twilio-node/issues/934#issuecomment-1615975913 the version of `dayjs` should be at least `v1.11.9` to avoid an error.
> fix: bump dayjs version (fixes #934)

- src/base/BaseTwilio.ts
A short description of what this PR does.
> fix: update security method validatessl

- .github/workflows/test-and-deploy.yml
Removed the LTS version from test and deploy pipeline as it was failing due to ongoing axios issue.
The Failed Run can be found [here](https://github.com/twilio/twilio-node/actions/runs/6789447330/job/18473999460?pr=971#step:6:18).
The Axios Issue can be found [here](https://github.com/axios/axios/issues/5929) 
> chore: Removed LTS version

- package.json
- src/base/RequestClient.ts
- Updates axios to 1.6.0
- Explicit TypeScript types to fix build/test.
> chore: Update axios to 1.6 to pull in fix for CVE 2023 45857

- README.md
Removed nodeio.co, twilioquest badges and added relevant badges for download counts and npm version
> chore: removed unnecessary badge and added relevant badges

- package.json
- spec/validation.spec.js
- src/webhooks/webhooks.ts
Currently, we use the [url-parse](https://www.npmjs.com/package/url-parse) package. This package is soft-deprecated - it's not actually throwing a deprecation warning, but the package's README urges users to switch to the [built-in URL parser](https://nodejs.org/api/url.html) that now exists. The changes have been taken from #998 
> chore: moving off from url-parse

- spec/validation.spec.js
- src/webhooks/webhooks.ts
Earlier if options is not passed in webhooks, it used to create options = {validate: true} but if options is passed and validate flag is missing (which expects that it will be taken true as it is the default value mentioned in the comments above), then it did not validate. Made a fix for the same.
> fix: corrected options.validate to default true

- .github/workflows/test-and-deploy.yml
- spec/cluster/public_oauth.spec.ts
- spec/unit/auth_strategy/BasicAuthStrategy.spec.ts
- spec/unit/auth_strategy/NoAuthStrategy.spec.ts
- spec/unit/auth_strategy/TokenAuthStrategy.spec.ts
- spec/unit/credential_provider/ClientCredentialProvider.spec.ts
- spec/unit/credential_provider/NoAuthCredentialProvider.spec.ts
- spec/unit/credential_provider/OrgsCredentialProvider.spec.ts
- spec/unit/http/bearer_token/ApiTokenManager.spec.ts
- spec/unit/http/bearer_token/OrgsTokenManager.spec.ts
Adds unit tests and cluster tests for node oauth for public apis
> chore: Add tests for node public oauth

- .github/workflows/test-and-deploy.yml
- spec/cluster/orgs_api.spec.ts
Adds cluster tests for orgs api
> chore: add cluster tests for orgs api

- spec/unit/webhooks/webhooks.spec.js
- src/webhooks/webhooks.ts
Update the `validateRequest()` function to fallback to a query string parser that does not escape single quotes if the request validation fails.
**Why?**
Query string values that contain single quotes (`'`) are escaped when using `new URL()`, but the Twilio server seems to generate the signature with the unescaped single quote value, causing the validation to fail in the scenario described in #1059
> fix(webhooks): validate Twilio signatures with escaped and unescaped query string values fixes #1059
